#!/bin/bash

#PBS -A mfb9_b_g_sc_default
#PBS -l nodes=1:ppn=1
#PBS -l pmem=64gb
#PBS -l walltime=24:00:00

#PBS -m ea

# Note the start time and location in case an error occurs
echo "Job started on `hostname` at `date`"

# Change to the directory we launched the script from and launch the simulation
cd $PBS_O_WORKDIR
./MaSim -i #POPULATION#-#BETA#-bfa.yml -s 1

# Note the end time
echo "Job ended at `date`"
